name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Run a multi-line script
      run: |
        docker pull microsoft/mssql-server-windows-express
        docker run -d -p 1433:1433 -e sa_password=demoPw -e ACCEPT_EULA=Y microsoft/mssql-server-windows-express
