name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Run a multi-line script
      run: |
        docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=yourStrong(!)Password' -p 1433:1433 -d mcr.microsoft.com/mssql/server:2017-latest
