name: "Pull Request Sorters"
on:
- pull_request

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: Gallimathias/PROrderAction@latest
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
